-- KnowledgeComponent 테이블 데이터
INSERT INTO knowledge_component (id, category, stage) VALUES
(1, 'LABIAL_1', '1.2.1'),
(2, 'VELAR_1', '1.2.1'),
(3, 'ALVEOLAR_1', '1.2.1'),
(4, 'PALATAL_1', '1.2.1'),
(5, 'ALVEOLAR_FRICATIVE_1', '1.2.1'),
(6, 'GLOTTAL_AND_ALVEOLAR_1', '1.2.1'),
(7, 'LABIAL_ONSET_1', '4.1'),
(8, 'VELAR_ONSET_1', '4.1'),
(9, 'ALVEOLAR_ONSET_1', '4.1'),
(10, 'PALATAL_ONSET_1', '4.1'),
(11, 'ALVEOLAR_FRICATIVE_ONSET_1', '4.1'),
(12, 'GLOTTAL_AND_ALVEOLAR_ONSET_1', '4.1'),
(13, 'LABIAL_CODA_1', '4.1'),
(14, 'VELAR_CODA_1', '4.1'),
(15, 'ALVEOLAR_CODA_1', '4.1'),
(16, 'PALATAL_CODA_1', '4.1'),
(17, 'ALVEOLAR_FRICATIVE_CODA_1', '4.1'),
(18, 'GLOTTAL_AND_ALVEOLAR_CODA_1', '4.1'),
(19, 'MONOPHTHONG_1', '1.1.1'),
(20, 'DIPHTHONG_1', '1.1.1'),
(21, 'MONOPHTHONG_NUCLEUS_1', '4.1'),
(22, 'DIPHTHONG_NUCLEUS_1', '4.1'),
(23, 'CLOSED_SYLLABLE', '3'),
(24, 'OPEN_SYLLABLE', '3'),
(25, 'LABIAL_2', '1.2.2'),
(26, 'VELAR_2', '1.2.2'),
(27, 'ALVEOLAR_2', '1.2.2'),
(28, 'PALATAL_2', '1.2.2'),
(29, 'ALVEOLAR_FRICATIVE_2', '1.2.2'),
(30, 'GLOTTAL_AND_ALVEOLAR_2', '1.2.2'),
(31, 'MONOPHTHONG_2', '1.1.2'),
(32, 'DIPHTHONG_2', '1.1.2'),
(33, 'LABIAL_ONSET_2', '4.2'),
(34, 'VELAR_ONSET_2', '4.2'),
(35, 'ALVEOLAR_ONSET_2', '4.2'),
(36, 'PALATAL_ONSET_2', '4.2'),
(37, 'ALVEOLAR_FRICATIVE_ONSET_2', '4.2'),
(38, 'GLOTTAL_AND_ALVEOLAR_ONSET_2', '4.2'),
(39, 'LABIAL_CODA_2', '4.2'),
(40, 'VELAR_CODA_2', '4.2'),
(41, 'ALVEOLAR_CODA_2', '4.2'),
(42, 'PALATAL_CODA_2', '4.2'),
(43, 'ALVEOLAR_FRICATIVE_CODA_2', '4.2'),
(44, 'GLOTTAL_AND_ALVEOLAR_CODA_2', '4.2'),
(21, 'MONOPHTHONG_NUCLEUS_2', '4.2'),
(22, 'DIPHTHONG_NUCLEUS_2', '4.2'),
ON CONFLICT (id) DO NOTHING;

INSERT INTO words (id, word, voice_url) VALUES
                                            (1, '사과', ''),
                                            (2, '바나나', ''),
                                            (3, '고양이', ''),
                                            (4, '강아지', ''),
                                            (5, '코끼리', ''),
                                            (6, '꽃', ''),
                                            (7, '정원', ''),
                                            (8, '집', ''),
                                            (9, '섬', ''),
                                            (10, '정글', ''),
                                            (11, '왕', ''),
                                            (12, '사자', ''),
                                            (13, '산', ''),
                                            (14, '밤', ''),
                                            (15, '바다', ''),
                                            (16, '피아노', ''),
                                            (17, '여왕', ''),
                                            (18, '강', ''),
                                            (19, '태양', ''),
                                            (20, '나무', ''),
                                            (21, '우산', ''),
                                            (22, '마을', ''),
                                            (23, '물', ''),
                                            (24, '노랑', ''),
                                            (25, '얼룩말', ''),
                                            (26, '책', ''),
                                            (27, '의자', ''),
                                            (28, '책상', ''),
                                            (29, '문', ''),
                                            (30, '지구', ''),
                                            (31, '불', ''),
                                            (32, '유리', ''),
                                            (33, '마음', ''),
                                            (34, '얼음', ''),
                                            (35, '기쁨', ''),
                                            (36, '열쇠', ''),
                                            (37, '빛', ''),
                                            (38, '달', ''),
                                            (39, '코', ''),
                                            (40, '오렌지', ''),
                                            (41, '종이', ''),
                                            (42, '조용함', ''),
                                            (43, '비', ''),
                                            (44, '눈', ''),
                                            (45, '테이블', ''),
                                            (46, '우주', ''),
                                            (47, '목소리', ''),
                                            (48, '바람', ''),
                                            (49, '해', ''),
                                            (50, '지역', ''),
                                            (51, '모험', ''),
                                            (52, '다리', ''),
                                            (53, '구름', ''),
                                            (54, '꿈', ''),
                                            (55, '에너지', ''),
                                            (56, '숲', ''),
                                            (57, '기타', ''),
                                            (58, '조화', ''),
                                            (59, '이미지', ''),
                                            (60, '여행', ''),
                                            (61, '지식', ''),
                                            (62, '편지', ''),
                                            (63, '음악', ''),
                                            (64, '자연', ''),
                                            (65, '기회', ''),
                                            (66, '평화', ''),
                                            (67, '질문', ''),
                                            (68, '무지개', ''),
                                            (69, '별', ''),
                                            (70, '시간', ''),
                                            (71, '단결', ''),
                                            (72, '승리', ''),
                                            (73, '지혜', ''),
                                            (74, '청춘', ''),
                                            (75, '정점', ''),
                                            (76, '균형', ''),
                                            (77, '용기', ''),
                                            (78, '운명', ''),
                                            (79, '감정', ''),
                                            (80, '자유', ''),
                                            (81, '우아함', ''),
                                            (82, '희망', ''),
                                            (83, '영감', ''),
                                            (84, '정의', ''),
                                            (85, '친절', ''),
                                            (86, '사랑', ''),
                                            (87, '기억', ''),
                                            (88, '고귀함', ''),
                                            (89, '열정', ''),
                                            (90, '현실', ''),
                                            (91, '정신', ''),
                                            (92, '진실', ''),
                                            (93, '가치', ''),
                                            (94, '경이', ''),
                                            (95, '탁월함', ''),
                                            (96, '믿음', ''),
                                            (97, '성장', ''),
                                            (98, '건강', ''),
                                            (99, '진실성', ''),
                                            (100, '힘', '')
    ON CONFLICT (id) DO NOTHING;

INSERT INTO phonemes (category, value, unicode, image_url, voice_url) VALUES
-- 기본 자음 (14개)
('consonant', 'ㄱ', 'U+3131', 'https://final-a206.s3.ap-northeast-2.amazonaws.com/consonantMouseImage/consonant_%E3%84%B1.png', NULL),   -- VELAR
('consonant', 'ㄴ', 'U+3134', 'https://final-a206.s3.ap-northeast-2.amazonaws.com/consonantMouseImage/consonant_%E3%84%B4.png', NULL),   -- ALVEOLAR
('consonant', 'ㄷ', 'U+3137', 'https://final-a206.s3.ap-northeast-2.amazonaws.com/consonantMouseImage/consonant_%E3%84%B7.png', NULL),   -- ALVEOLAR
('consonant', 'ㄹ', 'U+3139', 'https://final-a206.s3.ap-northeast-2.amazonaws.com/consonantMouseImage/consonant_%E3%84%B9.png', NULL),   -- GLOTTAL_AND_ALVEOLAR
('consonant', 'ㅁ', 'U+3141', 'https://final-a206.s3.ap-northeast-2.amazonaws.com/consonantMouseImage/consonant_%E3%85%81.png', NULL),   -- LABIAL
('consonant', 'ㅂ', 'U+3142', 'https://final-a206.s3.ap-northeast-2.amazonaws.com/consonantMouseImage/consonant_%E3%85%82.png', NULL),   -- LABIAL
('consonant', 'ㅅ', 'U+3145', 'https://final-a206.s3.ap-northeast-2.amazonaws.com/consonantMouseImage/consonant_%E3%85%85.png', NULL),   -- ALVEOLAR_FRICATIVE
('consonant', 'ㅇ', 'U+3147', 'https://final-a206.s3.ap-northeast-2.amazonaws.com/consonantMouseImage/consonant_%E3%85%87.png', NULL),   -- VELAR
('consonant', 'ㅈ', 'U+3148', 'https://final-a206.s3.ap-northeast-2.amazonaws.com/consonantMouseImage/consonant_%E3%85%88.png', NULL),   -- PALATAL
('consonant', 'ㅊ', 'U+314A', 'https://final-a206.s3.ap-northeast-2.amazonaws.com/consonantMouseImage/consonant_%E3%85%8A.png', NULL),   -- PALATAL
('consonant', 'ㅋ', 'U+314B', 'https://final-a206.s3.ap-northeast-2.amazonaws.com/consonantMouseImage/consonant_%E3%85%8B.png', NULL),   -- VELAR
('consonant', 'ㅌ', 'U+314C', 'https://final-a206.s3.ap-northeast-2.amazonaws.com/consonantMouseImage/consonant_%E3%85%8C.png', NULL),   -- ALVEOLAR
('consonant', 'ㅍ', 'U+314D', 'https://final-a206.s3.ap-northeast-2.amazonaws.com/consonantMouseImage/consonant_%E3%85%8D.png', NULL),   -- LABIAL
('consonant', 'ㅎ', 'U+314E', 'https://final-a206.s3.ap-northeast-2.amazonaws.com/consonantMouseImage/consonant_%E3%85%8E.png', NULL),   -- GLOTTAL_AND_ALVEOLAR
-- 쌍자음 (5개)
('consonant', 'ㄲ', 'U+3132', 'https://final-a206.s3.ap-northeast-2.amazonaws.com/consonantMouseImage/consonant_%E3%84%B2.png', NULL),   -- VELAR
('consonant', 'ㄸ', 'U+3138', 'https://final-a206.s3.ap-northeast-2.amazonaws.com/consonantMouseImage/consonant_%E3%84%B8.png', NULL),   -- ALVEOLAR
('consonant', 'ㅃ', 'U+3143', 'https://final-a206.s3.ap-northeast-2.amazonaws.com/consonantMouseImage/consonant_%E3%85%83.png', NULL),   -- LABIAL
('consonant', 'ㅆ', 'U+3146', 'https://final-a206.s3.ap-northeast-2.amazonaws.com/consonantMouseImage/consonant_%E3%85%86.png', NULL),   -- ALVEOLAR_FRICATIVE
('consonant', 'ㅉ', 'U+3149', 'https://final-a206.s3.ap-northeast-2.amazonaws.com/consonantMouseImage/consonant_%E3%85%89.png', NULL)    -- PALATAL
ON CONFLICT (value) DO NOTHING;

INSERT INTO phonemes (category, value, unicode, image_url, voice_url) VALUES
('vowel', 'ㅏ', 'U+314F', 'https://final-a206.s3.ap-northeast-2.amazonaws.com/vowelMouthImage/vowel_%E3%85%8F.png', NULL),
('vowel', 'ㅐ', 'U+3150', 'https://final-a206.s3.ap-northeast-2.amazonaws.com/vowelMouthImage/vowel_%E3%85%90.png', NULL),
('vowel', 'ㅑ', 'U+3151', 'https://final-a206.s3.ap-northeast-2.amazonaws.com/vowelMouthImage/vowel_%E3%85%91.png', NULL),
('vowel', 'ㅒ', 'U+3152', 'https://final-a206.s3.ap-northeast-2.amazonaws.com/vowelMouthImage/vowel_%E3%85%92.png', NULL),
('vowel', 'ㅓ', 'U+3153', 'https://final-a206.s3.ap-northeast-2.amazonaws.com/vowelMouthImage/vowel_%E3%85%93.png', NULL),
('vowel', 'ㅔ', 'U+3154', 'https://final-a206.s3.ap-northeast-2.amazonaws.com/vowelMouthImage/vowel_%E3%85%94.png', NULL),
('vowel', 'ㅕ', 'U+3155', 'https://final-a206.s3.ap-northeast-2.amazonaws.com/vowelMouthImage/vowel_%E3%85%95.png', NULL),
('vowel', 'ㅖ', 'U+3156', 'https://final-a206.s3.ap-northeast-2.amazonaws.com/vowelMouthImage/vowel_%E3%85%96.png', NULL),
('vowel', 'ㅗ', 'U+3157', 'https://final-a206.s3.ap-northeast-2.amazonaws.com/vowelMouthImage/vowel_%E3%85%97.png', NULL),
('vowel', 'ㅘ', 'U+3158', 'https://final-a206.s3.ap-northeast-2.amazonaws.com/vowelMouthImage/vowel_%E3%85%98.png', NULL),
('vowel', 'ㅙ', 'U+3159', 'https://final-a206.s3.ap-northeast-2.amazonaws.com/vowelMouthImage/vowel_%E3%85%99.png', NULL),
('vowel', 'ㅚ', 'U+315A', 'https://final-a206.s3.ap-northeast-2.amazonaws.com/vowelMouthImage/vowel_%E3%85%9A.png', NULL),
('vowel', 'ㅛ', 'U+315B', 'https://final-a206.s3.ap-northeast-2.amazonaws.com/vowelMouthImage/vowel_%E3%85%9B.png', NULL),
('vowel', 'ㅜ', 'U+315C', 'https://final-a206.s3.ap-northeast-2.amazonaws.com/vowelMouthImage/vowel_%E3%85%9C.png', NULL),
('vowel', 'ㅝ', 'U+315D', 'https://final-a206.s3.ap-northeast-2.amazonaws.com/vowelMouthImage/vowel_%E3%85%9D.png', NULL),
('vowel', 'ㅞ', 'U+315E', 'https://final-a206.s3.ap-northeast-2.amazonaws.com/vowelMouthImage/vowel_%E3%85%9E.png', NULL),
('vowel', 'ㅟ', 'U+315F', 'https://final-a206.s3.ap-northeast-2.amazonaws.com/vowelMouthImage/vowel_%E3%85%9F.png', NULL),
('vowel', 'ㅠ', 'U+3160', 'https://final-a206.s3.ap-northeast-2.amazonaws.com/vowelMouthImage/vowel_%E3%85%A0.png', NULL),
('vowel', 'ㅡ', 'U+3161', 'https://final-a206.s3.ap-northeast-2.amazonaws.com/vowelMouthImage/vowel_%E3%85%A1.png', NULL),
('vowel', 'ㅢ', 'U+3162', 'https://final-a206.s3.ap-northeast-2.amazonaws.com/vowelMouthImage/vowel_%E3%85%A2.png', NULL),
('vowel', 'ㅣ', 'U+3163', 'https://final-a206.s3.ap-northeast-2.amazonaws.com/vowelMouthImage/vowel_%E3%85%A3.png', NULL)
ON CONFLICT (value) DO NOTHING;
